# @format
branches:
  only:
    - master

os: linux
dist: focal
language: node_js
node_js:
  - 18

install:
  - npm install
  -  sudo apt-get install -y imagemagick graphicsmagick

jobs:
  include:
    - script:
        - npm run eslint
      name: 'Lint code sources'
    - script:
        - npm audit --audit-level=high
      name: 'Lightweight dependencies security audit'
    - script:
        - npm run validate-links
      name: 'Check link validity'
    - script:
        - npm run test-functional
    name: 'Check if the web app can start'
