# @format
branches:
  only:
    - master

os: linux
dist: focal
language: node_js
node_js:
  - 18

install:
  - npm install

jobs:
  include:
    - script:
        - npm run eslint
      name: 'Lint code sources'
    - script:
        - npm run assert-code
      name: 'Build and test code'
    - script:
        - npm audit --audit-level=high
      name: 'Lightweight dependencies security audit'
    - script:
        - npm run validate-links
