# @format
branches:
  only:
    - master

os: linux
dist: focal
language: node_js
node_js:
  - 14
  
env:
  - FAILURE_THRESHOLD=1
  
install:
  - npm install --global remark-cli remark-validate-links
  
jobs:
  include:
    - stage: client
      script:
        - cd ./client && npm install && npm run travis
    - stage: server
      script:
        - cd ./server && npm install && npm run travis
#    - stage: "Markdown link checks"
#      script:
#        - remark -u validate-links .
#        - |
#          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l` &&
#          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
#            exit 1;
#          fi    
