# @format
branches:
  only:
    - master

os: linux
dist: focal
language: node_js
node_js:
  - 14

jobs:
  include:
    - stage: client
      script:
        - cd ./client && npm install && npm run travis
    - stage: server
      script:
        - cd ./server && npm install && npm run travis